# Generated by Django 2.0 on 2019-07-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190724_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
