# Generated by Django 2.0 on 2019-07-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190726_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default='doctor.png', upload_to=''),
        ),
    ]
