# Generated by Django 2.0 on 2019-08-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
