# Generated by Django 3.0 on 2019-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_adminprofile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorProfile',
            new_name='ClientProfile',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='patient',
            field=models.BooleanField(default=False),
        ),
    ]
