# Generated by Django 3.0 on 2020-01-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20200111_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AddField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=20, max_digits=20)),
                ('qty', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.Image')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='Product.ProductVariant'),
        ),
    ]
