# Generated by Django 3.0 on 2020-01-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20200117_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_img',
        ),
        migrations.AddField(
            model_name='image',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
