# Generated by Django 3.0 on 2020-01-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20200130_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Product'),
        ),
    ]
