# Generated by Django 3.0 on 2020-01-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200131_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
